### ISSUE TITLE
Questions and suggestions:

### ISSUE THREAD

**Issue by APISeeker** [anothermartz/Easy-Wav2Lip#20]
1) Suggesiton: I think this project (the bat file) could benefit from the creation of a VENV, creating a venv will allow the libraries to not compete with other python libraries of your base python env. The bat file should check if the venv exist and work on it, if does not exist then create it.
2) Question 1: You mentioned using bing ai to help you create this, My experience is that bign ai tend to forget the context of the discussion so you cant have a long conversation with it, how did you manage? Maybe it was just small conversations at once?

2) Question 2: You mention cog wav2Lip , I think i had tried to use it once, but I was nevel able to make it work, proof:
![image](https://github.com/anothermartz/Easy-Wav2Lip/assets/145594487/30e347e4-b0f6-471e-b80c-8fa4caf170fe)

There is always an error about librosa or NUMPY versiosn, I have no idea what to fix, when I try to install lower versions of numpy it produces some error, if I leave it it does not run.. 
I would like to install that versions you mentioned just to try it (on build on it possibly)
can you:
     - help me install it, tell me which versions of python and which versions of the libraires you used to make it work in local, if you ever try?
     - Tell me which files I need from that repo (copy paste into another working repo) so I can try it easily and make it work without having to install the whole cog repo? Where do I put the models : "Visual quality"' and "Lipsync expert"? do I put them inside checkpoints folder aswell? 
edit: I made the cog wav2lip work.

3) You state that you had no python knowledge prior, but you had coding knowledge on other langauegs right? because otherwise that woudl be very surprising, a non coder could not do this even with gpt help.
Cheers

**Comment by anothermartz** [comment]
Hi, I don't know why I wasn't alerted to this thread and had to randomly find it when checking on the project.

I initially tried to use a venv but I kept running into issues that weren't there when I tried without. I can't remember specifically what, but that's why I don't use one, I understand that it would be better, but I hit a roadblock when trying.

When using Bing chat, I would start new chats asking specifically about the issue / feature I was working on, I provided all the relevant info for the specific thing I talked about as if it was the only thing I was doing.

I've only previously written a couple of things for AutoHotkey which is a very basic language for a specific tool, and I've edited existing lua code a little bit a long time ago, I was looking at official python syntax and stack overflow threads too, but really I was holding onto Bing as a crutch.

As time went on I relied on bing less and less as I got more familiar with python but I wouldn't be confident to try anything without it. Again I was more focused on asking very specific things and then sometimes got advice of how to implement it into existing code. Asking too much at once or going full auto by posting errors and copying code without reading it usually leads to nowhere (which happened a lot too). I think many non-coders could make a python project with chatGPT as long as they try and learn along side it and don't expect it will output fully working code all the time.

I'm glad you got cog-wav2lip working as I can't remember specifically how I did it, my focus was just getting it working in google colab.

**Comment by anothermartz** [comment]
Hi I have now figured out venv usage and have a largely untested version available here:

https://github.com/anothermartz/Easy-Wav2Lip/releases/tag/Easy-Wav2Lip-venvtest

Let me know if it works properly so I can use it as the standard Easy-Wav2Lip.bat file.
