### ISSUE TITLE
Why is my CPU usage so high? I have successfully installed CUDA and CUNDDN

### ISSUE THREAD

**Issue by FangXxun** [anothermartz/Easy-Wav2Lip#27]
Windows 10 
![17101244614994](https://github.com/anothermartz/Easy-Wav2Lip/assets/120164055/1f7adb01-7276-4f4d-9680-31d1343bdca4)

![image](https://github.com/anothermartz/Easy-Wav2Lip/assets/120164055/8f705796-bb98-4bdb-9d05-4cba405766d1)
![image](https://github.com/anothermartz/Easy-Wav2Lip/assets/120164055/e981e907-322b-46e7-82c8-523d28d31d50)

**Comment by anothermartz** [comment]
I have removed all references of using the CPU instead of Cuda because it's so slow I don't think it's worth supporting. So it shouldn't be choosing to use the CPU based on cuda availability. It would just fail instead.

What part of the Wav2Lip process is this? I know that some parts still use the CPU such as creating the mask and perhaps detecting the face, but the actual Wav2Lip lip syncing should be using the GPU.

**Comment by FangXxun** [comment]
it is strange,detecting face can achieve 11.31it/s,but the Processing Wav2lip only have 3it/s
![image](https://github.com/anothermartz/Easy-Wav2Lip/assets/120164055/762e0d65-d98f-4004-9c34-7df0143d5e6b)

**Comment by anothermartz** [comment]
> it is strange,detecting face can achieve 11.31it/s,but the Processing Wav2lip only have 3it/s
> ![image](https://github.com/anothermartz/Easy-Wav2Lip/assets/120164055/762e0d65-d98f-4004-9c34-7df0143d5e6b)
> 

Well detecting the face is a much simpler process than what Wav2Lip is doing, it's more of an algorithm than AI. Are you sure that when the main process is running, that your GPU isn't being utilised more?

**Comment by FangXxun** [comment]
My GPU will increase by over 1G，
But the CPU has always been high, almost 100%

**Comment by anothermartz** [comment]
The CPU usage is most likely due to Mediapipe as it is CPU based. Mediapipe is a face detection/tracking module that gives the result of the huge speedup and accuracy compared to the original Wav2Lip which used dlib.

So I think this is normal and is not an indication of an issue with the install or usage.
