### ISSUE TITLE
Have error

### ISSUE THREAD

**Issue by dend211** [anothermartz/Easy-Wav2Lip#36]
SystemExit: Step 1 has not been run in this instance! Please run step 1 each time you disconnect from a runtime.

Im launched step 1 but i still have this problem

**Comment by anothermartz** [comment]
Use the latest v8.2 colab!

[https://colab.research.google.com/github/anothermartz/Easy-Wav2Lip/blob/v8.2/Easy_Wav2Lip_v8.2.ipynb](https://colab.research.google.com/github/anothermartz/Easy-Wav2Lip/blob/v8.2/Easy_Wav2Lip_v8.2.ipynb)

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/anothermartz/Easy-Wav2Lip/blob/v8.2/Easy_Wav2Lip_v8.2.ipynb)

What you described was an issue that arose in v8.1 that I fixed with v8.2

See this for an explanation on what happened:
https://github.com/anothermartz/Easy-Wav2Lip/releases/tag/v8.2

**Comment by dend211** [comment]
Thanks!)
