### ISSUE TITLE
Is that possible to go through only Lip Enhancement ?

### ISSUE THREAD

**Issue by catyung** [anothermartz/Easy-Wav2Lip#8]
Hi @anothermartz , 

Thank you for your effort and its a very inspiring repo and project !

I am recently looking at Wav2Lip & GFP GAN as well, by looking at your "Mask" function, I am wondering if we can only go through GFP enhancement on the lip / mouth location only, instead of the whole face in order to save inference time?

Please advise.

Cheers!

Cat

**Comment by anothermartz** [comment]
Thanks for the suggestion! I'm guessing it will speed things up, although I'm not sure how gfpgan will treat lips without the rest of the face so I'll have to test that first.

**Comment by catyung** [comment]
> Thanks for the suggestion! I'm guessing it will speed things up, although I'm not sure how gfpgan will treat lips without the rest of the face so I'll have to test that first.

Thanks for your reply , I agreed , as GFPGAN is doing Face Restoration, I just tested with a mouth only pic and put it into GFPGAN for inference. I guess the output make sense 

![download](https://github.com/anothermartz/Easy-Wav2Lip/assets/49334769/4beb3d8e-9b0a-418c-9d79-6b62e43687ad)

**Comment by anothermartz** [comment]
Oh thanks for testing it for me, it looks like it works well!

I'm starting to work on doing this now :)

**Comment by anothermartz** [comment]
So I've tried this now and in my testing, gfgpan didn't recognize the mouth 100% of the time and so I'd get random frames where the mouth hadn't been upscaled.

The way I can combat this is to increase the size of the crop to include at least the bottom of the eyes, but at this point there really isn't a performance difference between that and the whole face and in fact, cropping the face a second time to the mouth actually makes inference time longer!

It also didn't smooth out the frame lines caused by wav2lip which is what I was expecting with upscaling out of the original crop bounds, dissapointed!

I will leave this version of upscaling as an "Experimental" quality option in v7 just in case someone finds a benefit in it, but I personally do not.

**Comment by catyung** [comment]
> So I've tried this now and in my testing, gfgpan didn't recognize the mouth 100% of the time and so I'd get random frames where the mouth hadn't been upscaled.
> 
> The way I can combat this is to increase the size of the crop to include at least the bottom of the eyes, but at this point there really isn't a performance difference between that and the whole face and in fact, cropping the face a second time to the mouth actually makes inference time longer!
> 
> It also didn't smooth out the frame lines caused by wav2lip which is what I was expecting with upscaling out of the original crop bounds, dissapointed!
> 
> I will leave this version of upscaling as an "Experimental" quality option in v7 just in case someone finds a benefit in it, but I personally do not.

Hi ! Thank you for your assistance ! I will definitely take a look at v7 and see if I can help ! :) <3
